Repository TGSAI/segy, pull requests merged in 2024-04, with the labels that each got.

#74 Update tests badge to use main branch
  README.md
Labels: documentation

#63 Refactor Tests
  docs/tutorials/creation.ipynb
  poetry.lock
  pyproject.toml
  src/segy/arrays.py
  src/segy/factory.py
  src/segy/file.py
  src/segy/ibm.py
  src/segy/indexing.py
  src/segy/schema/segy.py
  src/segy/schema/trace.py
  src/segy/standards/__init__.py
  src/segy/standards/mapping.py
  src/segy/standards/minimal.py
  src/segy/standards/registry.py
  src/segy/standards/rev1.py
  src/segy/transforms.py
  tests/__init__.py
  tests/conftest.py
  tests/main/conftest.py
  tests/main/test_indexing.py
  tests/main/test_segy_file.py
  tests/schema/conftest.py
  tests/schema/test_data_type.py
  tests/schema/test_header.py
  tests/schema/test_segy_descriptor.py
  tests/test_factory.py
  tests/test_ibm_float.py
  tests/test_indexing.py
  tests/test_schema_data_type.py
  tests/test_schema_header.py
  tests/test_schema_segy.py
  tests/test_schema_trace.py
  tests/test_segy_factory.py
  tests/test_segy_file.py
  tests/test_standards_registry.py
Labels: testing

#75 Update `typer` and `numba` to latest.
  poetry.lock
  pyproject.toml
Labels: dependencies

#77 Fix broken CI: Make CI tooling constraint paths absolute
  .github/workflows/tests.yaml
Labels: ci

#78 Override Numpy's copy method to `SegyArray` to ensure uninterpreted bytes are preserved.
  src/segy/arrays.py
  tests/test_arrays.py
Labels: bug

#79 Make fetched raw bytes mutable for downstream transforms
  src/segy/file.py
  src/segy/indexing.py
Labels: enhancement

#80 Make transforms in-place and remove unnecessary transforms to simplify logic
  src/segy/transforms.py
  tests/test_transforms.py
Labels: enhancement

#81 Refactor SEG-Y standard registration and retrieval and make it more strict
  src/segy/cli/dump.py
  src/segy/factory.py
  src/segy/file.py
  src/segy/schema/segy.py
  src/segy/standards/__init__.py
  src/segy/standards/minimal.py
  src/segy/standards/registry.py
  tests/test_schema_segy.py
  tests/test_segy_factory.py
  tests/test_segy_file.py
  tests/test_standards_registry.py
Labels: enhancement

#82 Update canonical SEG-Y header field names in SEGY standards revisions 0 and 1
  src/segy/standards/rev0.py
  src/segy/standards/rev1.py
Labels: refactoring

#84 Decoupled transformation logic from `SegyFile`
  src/segy/accessors.py
  src/segy/file.py
  tests/test_accessors.py
Labels: refactoring
