Repository TGSAI/segy, pull requests merged in 2024-03, with the labels that each got.

#22 bump patch version
  .github/workflows/tests.yaml
  README.md
  docs/index.md
  pyproject.toml
Labels: documentation

#24 Enhanced Metadata for PyPI
  pyproject.toml
Labels: documentation

#26 Improve Readme and Install Instructions
  README.md
  docs/installation.md
  pyproject.toml
Labels: documentation

#27 Add Codecov Token to CI
  .github/workflows/tests.yaml
Labels: ci

#28 Enhance Documentation
  README.md
  docs/api_reference.md
  docs/conf.py
  docs/data_models/data_type.md
  docs/data_models/file.md
  docs/data_models/header.md
  docs/data_models/trace.md
  docs/index.md
  docs/installation.md
  docs/settings.md
  src/segy/config.py
  src/segy/file.py
  src/segy/schema/__init__.py
  src/segy/schema/data_type.py
  src/segy/schema/header.py
  src/segy/schema/segy.py
  src/segy/schema/trace.py
  src/segy/standards/rev0.py
  src/segy/standards/rev1.py
  tests/conftest.py
  tests/schema/conftest.py
  tests/schema/test_header.py
Labels: documentation

#29 Populate remaining tests for schemas.
  tests/conftest.py
  tests/schema/conftest.py
  tests/schema/test_data_type.py
  tests/schema/test_header.py
  tests/schema/test_segy_descriptor.py
Labels: testing

#32 Refactor storage options and minor bug fixes
  docs/cli_usage.md
  docs/settings.md
  docs/tutorials/quickstart.ipynb
  src/segy/cli/dump.py
  src/segy/config.py
  src/segy/file.py
  src/segy/indexing.py
  src/segy/schema/__init__.py
  src/segy/schema/segy.py
Labels: bug, enhancement

#31 Fix sphinx-autobuild infinite loop bug
  noxfile.py
Labels: documentation

#40 Updated Conda installation instructions
  README.md
  docs/installation.md
Labels: documentation

#41 Fix package name typo
  docs/installation.md
Labels: documentation

#42 Remove duplicate pip extras instructions
  docs/installation.md
Labels: documentation

#48 Improve header decoding robustness
  src/segy/schema/header.py
Labels: bug

#49 Add Conda links to README
  README.md
Labels: documentation

#50 Generalize transforms and headers
  src/segy/arrays.py
  src/segy/config.py
  src/segy/file.py
  src/segy/header.py
  src/segy/indexing.py
  src/segy/transforms.py
  tests/main/test_header_accessor.py
  tests/main/test_segy_file.py
  tests/main/test_transforms.py
Labels: refactoring

#52 SEG-Y creation functionality
  docs/api_reference.md
  docs/requirements.txt
  docs/tutorials/creation.ipynb
  docs/tutorials/index.md
  poetry.lock
  pyproject.toml
  src/segy/__init__.py
  src/segy/factory.py
  src/segy/file.py
  src/segy/ibm.py
  src/segy/indexing.py
  src/segy/standards/rev0.py
  src/segy/transforms.py
  src/segy/typing.py
  tests/main/test_transforms.py
  tests/test_factory.py
Labels: enhancement

#54 Downgrade `numba`to 0.59.0
  poetry.lock
  pyproject.toml
Labels: dependencies

#56 Adjust module doctoring whitespaces
  src/segy/cli/common.py
  src/segy/schema/__init__.py
  src/segy/schema/base.py
  src/segy/schema/trace.py
  src/segy/standards/__init__.py
  src/segy/standards/registry.py
  tests/conftest.py
  tests/main/test_ibm_ieee.py
  tests/main/test_indexing.py
  tests/schema/test_data_type.py
  tests/schema/test_header.py
  tests/schema/test_segy_descriptor.py
  tests/standards/test_registry.py
Labels: style

#57 Refactor endianness, byte swaps, and indexers to be more standardized.
  docs/tutorials/creation.ipynb
  docs/tutorials/quickstart.ipynb
  src/segy/arrays.py
  src/segy/cli/dump.py
  src/segy/config.py
  src/segy/factory.py
  src/segy/file.py
  src/segy/indexing.py
  src/segy/schema/__init__.py
  src/segy/schema/base.py
  src/segy/schema/data_type.py
  src/segy/schema/segy.py
  src/segy/schema/trace.py
  src/segy/standards/rev0.py
  src/segy/standards/rev1.py
  src/segy/transforms.py
  tests/conftest.py
  tests/main/conftest.py
  tests/main/test_indexing.py
  tests/main/test_segy_file.py
  tests/schema/conftest.py
  tests/schema/test_data_type.py
  tests/schema/test_header.py
  tests/schema/test_segy_descriptor.py
  tests/test_factory.py
  tests/test_transforms.py
Labels: refactoring

#59 Write number of samples are sample rate to trace header only if field exists
  src/segy/factory.py
Labels: bug

#60 Support for handling IBM float trace headers
  src/segy/file.py
  tests/test_transforms.py
Labels: enhancement

#61 Bump minimum `typer` and `poetry` versions
  docs/requirements.txt
  poetry.lock
  pyproject.toml
Labels: dependencies
